GET http://localhost:8080/api/users/4604daeb-b359-4471-964c-e6acdf8af1d0/data
Client-Id: SpTrivOXp7QEYuLboGlfi7Wo
SHA1-Hash-Security: 44e9609720703953947bc1e492135451eac0edd2

###

POST http://localhost:8080/api/create-key
Content-Type: application/json

{
    "uuid" : "4604daeb-b359-4471-964c-e6acdf8af1d0",
    "username" : "adyowowk@gmail.com",
    "password" : "Orchidgem-213" 
}

###
POST http://localhost:8080/api/register
Content-Type: application/json

{
    "username" : "admin",
    "email" : "adyowok@gmail.com",
    "password" : "Password213",
    "passwordRepeated" : "Password213",
    "uuid" : "4604daeb-b359-4471-964c-e6acdf8af1d2"
}

###
PATCH http://localhost:8080/api/users/4604daeb-b359-4471-964c-e6acdf8af1d0/online
Content-Type: application/json

{
    "online" : true
}